FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY Connect4.Blazor.csproj .
RUN dotnet restore "Connect4.Blazor.csproj"
COPY . .
RUN dotnet build "Connect4.Blazor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Connect4.Blazor.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Connect4.Blazor.dll"]